presubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: check-operand-deployment-lifecycle-manager
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test check-operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/cicdtest/check-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-operand-deployment-lifecycle-manager-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test test-operand-deployment-lifecycle-manager-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: kind-e2e-test-operand-deployment-lifecycle-manager-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test e2e-test-kind-operand-deployment-lifecycle-manager-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - e2e-test-kind
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?e2e-test-kind(?:.*?)?$'
postsubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: image-operand-deployment-lifecycle-manager-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
  - name: image-operand-deployment-lifecycle-manager-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
  - name: image-operand-deployment-lifecycle-manager-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-operand-deployment-lifecycle-manager-postsubmit
    cluster: default
    branches:
    - ^master$
    - ^release-sc2$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-1.13$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/cicdtest/build-tool:v20250507-7dfc94eec
        name: ""
        securityContext:
          privileged: true
